swiftmailer:
    host: host
    port: 25
    username: username
    password: password
    encryption:
    auth_mode: login

instagram:
    user_id: userid
    access_token: accesstoken
    api_base_url: https://api.instagram.com